In [34]:
import nltk # Natural Language Toolkit
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt_tab')
import pandas as pd
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from wordcloud import WordCloud, STOPWORDS
import seaborn as sns
import matplotlib.pyplot as plt
import re # Regular Expression
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline
!pip install WordCloud
from wordcloud import WordCloud,STOPWORDS
import matplotlib.pyplot as plt

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

Requirement already satisfied: WordCloud in /usr/local/lib/python3.12/dist-packages (1.9.6)
Requirement already satisfied: numpy>=1.19.3 in /usr/local/lib/python3.12/dist-packages (from WordCloud) (2.0.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from WordCloud) (11.3.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from WordCloud) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->WordCloud) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->WordCloud) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->WordCloud) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->WordCloud) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->WordCloud) (26.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->WordCloud) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->WordCloud) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->WordCloud) (1.17.0)

In [35]:
df = pd.read_excel("drugsCom_raw.xlsx")

In [36]:
df.head(10)

,Unnamed: 0,drugName,condition,review,rating,date,usefulCount
0,206461,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combination of Bystolic 5 Mg and Fish Oil""",9,2012-05-20,27
1,95260,Guanfacine,ADHD,"""My son is halfway through his fourth week of Intuniv. We became concerned when he began this last week, when he started taking the highest dose he will be on. For two days, he could hardly get out of bed, was very cranky, and slept for nearly 8 hours on a drive home from school vacation (very unusual for him.) I called his doctor on Monday morning and she said to stick it out a few days. See how he did at school, and with getting up in the morning. The last two days have been problem free. He is MUCH more agreeable than ever. He is less emotional (a good thing), less cranky. He is remembering all the things he should. Overall his behavior is better. \nWe have tried many different medications and so far this is the most effective.""",8,2010-04-27,192
2,92703,Lybrel,Birth Control,"""I used to take another oral contraceptive, which had 21 pill cycle, and was very happy- very light periods, max 5 days, no other side effects. But it contained hormone gestodene, which is not available in US, so I switched to Lybrel, because the ingredients are similar. When my other pills ended, I started Lybrel immediately, on my first day of period, as the instructions said. And the period lasted for two weeks. When taking the second pack- same two weeks. And now, with third pack things got even worse- my third period lasted for two weeks and now it&#039;s the end of the third week- I still have daily brown discharge.\nThe positive side is that I didn&#039;t have any other side effects. The idea of being period free was so tempting... Alas.""",5,2009-12-14,17
3,138000,Ortho Evra,Birth Control,"""This is my first time using any form of birth control. I&#039;m glad I went with the patch, I have been on it for 8 months. At first It decreased my libido but that subsided. The only downside is that it made my periods longer (5-6 days to be exact) I used to only have periods for 3-4 days max also made my cramps intense for the first two days of my period, I never had cramps before using birth control. Other than that in happy with the patch""",8,2015-11-03,10
4,35696,Buprenorphine / naloxone,Opiate Dependence,"""Suboxone has completely turned my life around. I feel healthier, I&#039;m excelling at my job and I always have money in my pocket and my savings account. I had none of those before Suboxone and spent years abusing oxycontin. My paycheck was already spent by the time I got it and I started resorting to scheming and stealing to fund my addiction. All that is history. If you&#039;re ready to stop, there&#039;s a good chance that suboxone will put you on the path of great life again. I have found the side-effects to be minimal compared to oxycontin. I&#039;m actually sleeping better. Slight constipation is about it for me. It truly is amazing. The cost pales in comparison to what I spent on oxycontin.""",9,2016-11-27,37
5,155963,Cialis,Benign Prostatic Hyperplasia,"""2nd day on 5mg started to work with rock hard erections however experianced headache, lower bowel preassure. 3rd day erections would wake me up &amp; hurt! Leg/ankles aches severe lower bowel preassure like you need to go #2 but can&#039;t! Enjoyed the initial rockhard erections but not at these side effects or $230 for months supply! I&#039;m 50 &amp; work out 3Xs a week. Not worth side effects!""",2,2015-11-28,43
6,165907,Levonorgestrel,Emergency Contraception,"""He pulled out, but he cummed a bit in me. I took the Plan B 26 hours later, and took a pregnancy test two weeks later - - I&#039;m pregnant.""",1,2017-03-07,5
7,102654,Aripiprazole,Bipolar Disorde,"""Abilify changed my life. There is hope. I was on Zoloft and Clonidine when I first started Abilify at the age of 15.. Zoloft for depression and Clondine to manage my complete rage. My moods were out of control. I was depressed and hopeless one second and then mean, irrational, and full of rage the next. My Dr. prescribed me 2mg of Abilify and from that point on I feel like I have been cured though I know I&#039;m not.. Bi-polar disorder is a constant battle. I know Abilify works for me because I have tried to get off it and lost complete control over my emotions. Went back on it and I was golden again. I am on 5mg 2x daily. I am now 21 and better than I have ever been in the past. Only side effect is I like to eat a lot.""",10,2015-03-14,32
8,74811,Keppra,Epilepsy,""" I Ve had nothing but problems with the Keppera : constant shaking in my arms &amp; legs &amp; pins &amp; needles feeling in my arms &amp; legs severe light headedness no appetite &amp; etc.""",1,2016-08-09,11
9,48928,Ethinyl estradiol / levonorgestrel,Birth Control,"""I had been on the pill for many years. When my doctor changed my RX to chateal, it was as effective. It really did help me by completely clearing my acne, this takes about 6 months though. I did not gain extra weight, or develop any emotional health issues. I stopped taking it bc I started using a more natural method of birth control, but started to take it bc I hate that my acne came back at age 28. I really hope symptoms like depression, or weight gain do not begin to affect me as I am older now. I&#039;m also naturally moody, so this may worsen things. I was in a negative mental rut today. Also I hope this doesn&#039;t push me over the edge, as I believe I am depressed. Hopefully it&#039;ll be just like when I was younger.""",8,2016-12-08,1

In [37]:
df = df.drop(['Unnamed: 0','rating','date','usefulCount'],axis = 1)

In [38]:
df.head(10)

,drugName,condition,review
0,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combination of Bystolic 5 Mg and Fish Oil"""
1,Guanfacine,ADHD,"""My son is halfway through his fourth week of Intuniv. We became concerned when he began this last week, when he started taking the highest dose he will be on. For two days, he could hardly get out of bed, was very cranky, and slept for nearly 8 hours on a drive home from school vacation (very unusual for him.) I called his doctor on Monday morning and she said to stick it out a few days. See how he did at school, and with getting up in the morning. The last two days have been problem free. He is MUCH more agreeable than ever. He is less emotional (a good thing), less cranky. He is remembering all the things he should. Overall his behavior is better. \nWe have tried many different medications and so far this is the most effective."""
2,Lybrel,Birth Control,"""I used to take another oral contraceptive, which had 21 pill cycle, and was very happy- very light periods, max 5 days, no other side effects. But it contained hormone gestodene, which is not available in US, so I switched to Lybrel, because the ingredients are similar. When my other pills ended, I started Lybrel immediately, on my first day of period, as the instructions said. And the period lasted for two weeks. When taking the second pack- same two weeks. And now, with third pack things got even worse- my third period lasted for two weeks and now it&#039;s the end of the third week- I still have daily brown discharge.\nThe positive side is that I didn&#039;t have any other side effects. The idea of being period free was so tempting... Alas."""
3,Ortho Evra,Birth Control,"""This is my first time using any form of birth control. I&#039;m glad I went with the patch, I have been on it for 8 months. At first It decreased my libido but that subsided. The only downside is that it made my periods longer (5-6 days to be exact) I used to only have periods for 3-4 days max also made my cramps intense for the first two days of my period, I never had cramps before using birth control. Other than that in happy with the patch"""
4,Buprenorphine / naloxone,Opiate Dependence,"""Suboxone has completely turned my life around. I feel healthier, I&#039;m excelling at my job and I always have money in my pocket and my savings account. I had none of those before Suboxone and spent years abusing oxycontin. My paycheck was already spent by the time I got it and I started resorting to scheming and stealing to fund my addiction. All that is history. If you&#039;re ready to stop, there&#039;s a good chance that suboxone will put you on the path of great life again. I have found the side-effects to be minimal compared to oxycontin. I&#039;m actually sleeping better. Slight constipation is about it for me. It truly is amazing. The cost pales in comparison to what I spent on oxycontin."""
5,Cialis,Benign Prostatic Hyperplasia,"""2nd day on 5mg started to work with rock hard erections however experianced headache, lower bowel preassure. 3rd day erections would wake me up &amp; hurt! Leg/ankles aches severe lower bowel preassure like you need to go #2 but can&#039;t! Enjoyed the initial rockhard erections but not at these side effects or $230 for months supply! I&#039;m 50 &amp; work out 3Xs a week. Not worth side effects!"""
6,Levonorgestrel,Emergency Contraception,"""He pulled out, but he cummed a bit in me. I took the Plan B 26 hours later, and took a pregnancy test two weeks later - - I&#039;m pregnant."""
7,Aripiprazole,Bipolar Disorde,"""Abilify changed my life. There is hope. I was on Zoloft and Clonidine when I first started Abilify at the age of 15.. Zoloft for depression and Clondine to manage my complete rage. My moods were out of control. I was depressed and hopeless one second and then mean, irrational, and full of rage the next. My Dr. prescribed me 2mg of Abilify and from that point on I feel like I have been cured though I know I&#039;m not.. Bi-polar disorder is a constant battle. I know Abilify works for me because I have tried to get off it and lost complete control over my emotions. Went back on it and I was golden again. I am on 5mg 2x daily. I am now 21 and better than I have ever been in the past. Only side effect is I like to eat a lot."""
8,Keppra,Epilepsy,""" I Ve had nothing but problems with the Keppera : constant shaking in my arms &amp; legs &amp; pins &amp; needles feeling in my arms &amp; legs severe light headedness no appetite &amp; etc."""
9,Ethinyl estradiol / levonorgestrel,Birth Control,"""I had been on the pill for many years. When my doctor changed my RX to chateal, it was as effective. It really did help me by completely clearing my acne, this takes about 6 months though. I did not gain extra weight, or develop any emotional health issues. I stopped taking it bc I started using a more natural method of birth control, but started to take it bc I hate that my acne came back at age 28. I really hope symptoms like depression, or weight gain do not begin to affect me as I am older now. I&#039;m also naturally moody, so this may worsen things. I was in a negative mental rut today. Also I hope this doesn&#039;t push me over the edge, as I believe I am depressed. Hopefully it&#039;ll be just like when I was younger."""

In [39]:
filtered_df = df[df['condition'].isin(['Depression','High Blood Pressure','Diabetes, Type 2'])]
filtered_df = filtered_df.reset_index(drop=True)
print(filtered_df.index)

RangeIndex(start=0, stop=13944, step=1)

In [40]:
filtered_df.head(10)

,drugName,condition,review
0,L-methylfolate,Depression,"""I have taken anti-depressants for years, with some improvement but mostly moderate to severe side affects, which makes me go off them.\n\nI only take Cymbalta now mostly for pain.\n\nWhen I began Deplin, I noticed a major improvement overnight. More energy, better disposition, and no sinking to the low lows of major depression. I have been taking it for about 3 months now and feel like a normal person for the first time ever. Best thing, no side effects."""
1,Sertraline,Depression,"""1 week on Zoloft for anxiety and mood swings. I take 50mg in the mornings with my breakfast. Nausea on day one but that subsided as the week went on. I get the jitters about 2 hrs after taking it followed by yawning. I feel much better though and less angry/stressed."""
2,Venlafaxine,Depression,"""my gp started me on Venlafaxine yesterday to help with depression and the change,a hour after taking them i was feeling very sick couldn,t stomach food or fluids, thought keep it up as she told me they did come with some side effects which would get better,took another one last night and was so ill i couldn,t stand ,being sick sweating shaking thought i was going to pass out. Did get some sleep hopeing to feel better this morning,took another one and felt so spaced out dry mouth shaking ,sick, so booked in to see gp again to make sure i should be feeling like this, only to find out she had put me on the wrong dose should have been on 37.5mg was put on 150mg, now on right dose hope this will be better"""
3,Dulaglutide,"Diabetes, Type 2","""Hey Guys, It&#039;s been 4 months since my last post as I wanted to give it a few months to see how this was going to work. So, I have been on Trulicity for six months now with Metformin. When I hit the five month period the diarrhea, gas, sulphur belching finally subsided. I now longer have any of those side effects. However, I still haven&#039;t lost any weight at all, but I think that was because when I first started Trulicity I was taking it with Glimepiride and that one has a side effect of weight gain so I think the two meds were fighting each other lol. I have been back on the Metformin with Trulicity for about a week now, so we will see what this does. I was diagnosed as stage 3 chronic kidney disease (CKD 3) so I am watching diet closely."""
4,Effexor XR,Depression,"""This medicine saved my life. I was at my wits end with anti-depressants and was ready to give up. My doctor finally prescribed me this after many failed medications, I am so glad she did. I honestly do not know where I would be without Effexor XR. Side effects were very mild compared to other anti-depressants I tried. I was drowsy for the first couple days, but it was tolerable. I highly recommend this for severe depression. I would also like to mention for people to realize there is light at the end of the tunnel and YOU WILL GET BETTER, and to never give up."""
5,Wellbutrin,Depression,"""Started taking it and I slept well at night and awoke early around 5 to start my day happily. But come 8 am and I am drowsy and needed to take already two hrs nap. Awake and resume\n\nMy day with not much difficulties. Than st 2 pm again I needed a nap? So how was I gonna make it to work and my appointments too ? I went cold turkey. Felt much better after that. Only to crash again. I did try other anti depressants including pristique. But I suffered with insomnia with these meds. I know I need to start again but so confused if I should resume welbutrin"""
6,Aripiprazole,Depression,"""Intake Effexor XR 375 mg, and lorazepam for depression and anxiety. My doctor added Abilify and I took it in mornings. It made me foggy. I moved it to Bertie and sleep better overall. I have noticed an increase in irritability which equates to feeling extremely angry by 3 pm daily. I&#039;ve rearranged my lorazepam to reduce that but need more time. I&#039;m also having restlessness which almost feels manic. We shall see. Increased cravings for sweets."""
7,Amlodipine / olmesartan,High Blood Pressure,"""My blood pressure has been around 160/100. Doctor prescribed Azor 40/10. Just 4 hrs later my reading showed 120/82. I was amazed. I am now on it daily. Thanks to Azor."""
8,Desvenlafaxine,Depression,"""This medication is amazing! After 3 days of being extremely sick, I started to feel amazing, I am now 1 month into it and am so happy all the time and have no depressive thoughts at all. It kind of blocks out any sad thoughts. Works perfectly for me."""
9,Dulaglutide,"Diabetes, Type 2","""I was recently referred to a endocrinologist and he started me on Trulicity and Jardiance. I&#039;ve tried to take Byetta in the past but had to stop because it made me very sick. I lost weight. But that was because I was throwing up all day. Effective weight loss method but I do NOT recommend it! \nI&#039;ve taken one dose of Trulicity and while I do have mild nausea it is not bad and I have switched from coffee to green tea in the morning. Really helps. That I would recommend. Sugar levels have not dropped significantly but they are dropping. Guess one week won&#039;t work wonders and I have to wait a bit. I don&#039;t know if it is the Trulicity or the Jardiance or the combo of both but I have managed to lose 7 pounds in 5 days."""

In [41]:
filtered_df.isnull().sum()

drugName     0
condition    0
review       0
dtype: int64

In [42]:
filtered_df.duplicated().sum()

np.int64(1)

In [43]:
filtered_df[filtered_df.duplicated()]

,drugName,condition,review
12413,Fluoxetine,Depression,"""I have suffered from severe depression/anxiety for 9 years now. I also suffer from PTSD. I have tried almost everything out there, and Prozac is the only antidepressant that I can take and that works for me. I am very sensitive to medication, and I&#039;m glad I have found at least one medication that helps my severe depression. It helps motivate me and keeps me alive. I have been on 10 mg for a long time, and then recently went to 20 mg. I think I need to increase my dosage even more so. But it has been the only reliable medication I have ever taken, and for the longest duration."""

In [44]:
filtered_df = filtered_df.drop_duplicates()

In [45]:
filtered_df.duplicated().sum()

np.int64(0)

In [46]:
filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13943 entries, 0 to 13943
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   drugName   13943 non-null  object
 1   condition  13943 non-null  object
 2   review     13943 non-null  object
dtypes: object(3)
memory usage: 435.7+ KB

In [47]:
lemma = WordNetLemmatizer()

In [48]:
range(len(filtered_df))

range(0, 13943)

In [49]:
new = filtered_df['review'][0].split()
new

['"I',
 'have',
 'taken',
 'anti-depressants',
 'for',
 'years,',
 'with',
 'some',
 'improvement',
 'but',
 'mostly',
 'moderate',
 'to',
 'severe',
 'side',
 'affects,',
 'which',
 'makes',
 'me',
 'go',
 'off',
 'them.',
 'I',
 'only',
 'take',
 'Cymbalta',
 'now',
 'mostly',
 'for',
 'pain.',
 'When',
 'I',
 'began',
 'Deplin,',
 'I',
 'noticed',
 'a',
 'major',
 'improvement',
 'overnight.',
 'More',
 'energy,',
 'better',
 'disposition,',
 'and',
 'no',
 'sinking',
 'to',
 'the',
 'low',
 'lows',
 'of',
 'major',
 'depression.',
 'I',
 'have',
 'been',
 'taking',
 'it',
 'for',
 'about',
 '3',
 'months',
 'now',
 'and',
 'feel',
 'like',
 'a',
 'normal',
 'person',
 'for',
 'the',
 'first',
 'time',
 'ever.',
 'Best',
 'thing,',
 'no',
 'side',
 'effects."']

In [50]:
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

stop_words = set(stopwords.words('english'))
lemma = WordNetLemmatizer()

def clean_text(text):

    text = re.sub('[^a-zA-Z]', ' ', text)

    text = text.lower()

    words = word_tokenize(text)

    words = [lemma.lemmatize(word) for word in words if word not in stop_words]

    return " ".join(words)

In [51]:
from sklearn.base import BaseEstimator, TransformerMixin

class TextCleaner(BaseEstimator, TransformerMixin):

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        return [clean_text(text) for text in X]

In [52]:
pd.set_option('display.max_colwidth', None)

In [53]:
filtered_df['drugName'] = filtered_df['drugName'].str.lower()

filtered_df['combined'] = filtered_df['drugName'] + " " + filtered_df['review']

In [54]:
filtered_df.head(10)

,drugName,condition,review,combined
0,l-methylfolate,Depression,"""I have taken anti-depressants for years, with some improvement but mostly moderate to severe side affects, which makes me go off them.\n\nI only take Cymbalta now mostly for pain.\n\nWhen I began Deplin, I noticed a major improvement overnight. More energy, better disposition, and no sinking to the low lows of major depression. I have been taking it for about 3 months now and feel like a normal person for the first time ever. Best thing, no side effects.""","l-methylfolate ""I have taken anti-depressants for years, with some improvement but mostly moderate to severe side affects, which makes me go off them.\n\nI only take Cymbalta now mostly for pain.\n\nWhen I began Deplin, I noticed a major improvement overnight. More energy, better disposition, and no sinking to the low lows of major depression. I have been taking it for about 3 months now and feel like a normal person for the first time ever. Best thing, no side effects."""
1,sertraline,Depression,"""1 week on Zoloft for anxiety and mood swings. I take 50mg in the mornings with my breakfast. Nausea on day one but that subsided as the week went on. I get the jitters about 2 hrs after taking it followed by yawning. I feel much better though and less angry/stressed.""","sertraline ""1 week on Zoloft for anxiety and mood swings. I take 50mg in the mornings with my breakfast. Nausea on day one but that subsided as the week went on. I get the jitters about 2 hrs after taking it followed by yawning. I feel much better though and less angry/stressed."""
2,venlafaxine,Depression,"""my gp started me on Venlafaxine yesterday to help with depression and the change,a hour after taking them i was feeling very sick couldn,t stomach food or fluids, thought keep it up as she told me they did come with some side effects which would get better,took another one last night and was so ill i couldn,t stand ,being sick sweating shaking thought i was going to pass out. Did get some sleep hopeing to feel better this morning,took another one and felt so spaced out dry mouth shaking ,sick, so booked in to see gp again to make sure i should be feeling like this, only to find out she had put me on the wrong dose should have been on 37.5mg was put on 150mg, now on right dose hope this will be better""","venlafaxine ""my gp started me on Venlafaxine yesterday to help with depression and the change,a hour after taking them i was feeling very sick couldn,t stomach food or fluids, thought keep it up as she told me they did come with some side effects which would get better,took another one last night and was so ill i couldn,t stand ,being sick sweating shaking thought i was going to pass out. Did get some sleep hopeing to feel better this morning,took another one and felt so spaced out dry mouth shaking ,sick, so booked in to see gp again to make sure i should be feeling like this, only to find out she had put me on the wrong dose should have been on 37.5mg was put on 150mg, now on right dose hope this will be better"""
3,dulaglutide,"Diabetes, Type 2","""Hey Guys, It&#039;s been 4 months since my last post as I wanted to give it a few months to see how this was going to work. So, I have been on Trulicity for six months now with Metformin. When I hit the five month period the diarrhea, gas, sulphur belching finally subsided. I now longer have any of those side effects. However, I still haven&#039;t lost any weight at all, but I think that was because when I first started Trulicity I was taking it with Glimepiride and that one has a side effect of weight gain so I think the two meds were fighting each other lol. I have been back on the Metformin with Trulicity for about a week now, so we will see what this does. I was diagnosed as stage 3 chronic kidney disease (CKD 3) so I am watching diet closely.""","dulaglutide ""Hey Guys, It&#039;s been 4 months since my last post as I wanted to give it a few months to see how this was going to work. So, I have been on Trulicity for six months now with Metformin. When I hit the five month period the diarrhea, gas, sulphur belching finally subsided. I now longer have any of those side effects. However, I still haven&#039;t lost any weight at all, but I think that was because when I first started Trulicity I was taking it with Glimepiride and that one has a side effect of weight gain so I think the two meds were fighting each other lol. I have been back on the Metformin with Trulicity for about a week now, so we will see what this does. I was diagnosed as stage 3 chronic kidney disease (CKD 3) so I am watching diet closely."""
4,effexor xr,Depression,"""This medicine saved my life. I was at my wits end with anti-depressants and was ready to give up. My doctor finally prescribed me this after many failed medications, I am so glad she did. I honestly do not know where I would be without Effexor XR. Side effects were very mild compared to other anti-depressants I tried. I was drowsy for the first couple days, but it was tolerable. I highly recommend this for severe depression. I would also like to mention for people to realize there is light at the end of the tunnel and YOU WILL GET BETTER, and to never give up.""","effexor xr ""This medicine saved my life. I was at my wits end with anti-depressants and was ready to give up. My doctor finally prescribed me this after many failed medications, I am so glad she did. I honestly do not know where I would be without Effexor XR. Side effects were very mild compared to other anti-depressants I tried. I was drowsy for the first couple days, but it was tolerable. I highly recommend this for severe depression. I would also like to mention for people to realize there is light at the end of the tunnel and YOU WILL GET BETTER, and to never give up."""
5,wellbutrin,Depression,"""Started taking it and I slept well at night and awoke early around 5 to start my day happily. But come 8 am and I am drowsy and needed to take already two hrs nap. Awake and resume\n\nMy day with not much difficulties. Than st 2 pm again I needed a nap? So how was I gonna make it to work and my appointments too ? I went cold turkey. Felt much better after that. Only to crash again. I did try other anti depressants including pristique. But I suffered with insomnia with these meds. I know I need to start again but so confused if I should resume welbutrin""","wellbutrin ""Started taking it and I slept well at night and awoke early around 5 to start my day happily. But come 8 am and I am drowsy and needed to take already two hrs nap. Awake and resume\n\nMy day with not much difficulties. Than st 2 pm again I needed a nap? So how was I gonna make it to work and my appointments too ? I went cold turkey. Felt much better after that. Only to crash again. I did try other anti depressants including pristique. But I suffered with insomnia with these meds. I know I need to start again but so confused if I should resume welbutrin"""
6,aripiprazole,Depression,"""Intake Effexor XR 375 mg, and lorazepam for depression and anxiety. My doctor added Abilify and I took it in mornings. It made me foggy. I moved it to Bertie and sleep better overall. I have noticed an increase in irritability which equates to feeling extremely angry by 3 pm daily. I&#039;ve rearranged my lorazepam to reduce that but need more time. I&#039;m also having restlessness which almost feels manic. We shall see. Increased cravings for sweets.""","aripiprazole ""Intake Effexor XR 375 mg, and lorazepam for depression and anxiety. My doctor added Abilify and I took it in mornings. It made me foggy. I moved it to Bertie and sleep better overall. I have noticed an increase in irritability which equates to feeling extremely angry by 3 pm daily. I&#039;ve rearranged my lorazepam to reduce that but need more time. I&#039;m also having restlessness which almost feels manic. We shall see. Increased cravings for sweets."""
7,amlodipine / olmesartan,High Blood Pressure,"""My blood pressure has been around 160/100. Doctor prescribed Azor 40/10. Just 4 hrs later my reading showed 120/82. I was amazed. I am now on it daily. Thanks to Azor.""","amlodipine / olmesartan ""My blood pressure has been around 160/100. Doctor prescribed Azor 40/10. Just 4 hrs later my reading showed 120/82. I was amazed. I am now on it daily. Thanks to Azor."""
8,desvenlafaxine,Depression,"""This medication is amazing! After 3 days of being extremely sick, I started to feel amazing, I am now 1 month into it and am so happy all the time and have no depressive thoughts at all. It kind of blocks out any sad thoughts. Works perfectly for me.""","desvenlafaxine ""This medication is amazing! After 3 days of being extremely sick, I started to feel amazing, I am now 1 month into it and am so happy all the time and have no depressive thoughts at all. It kind of blocks out any sad thoughts. Works perfectly for me."""
9,dulaglutide,"Diabetes, Type 2","""I was recently referred to a endocrinologist and he started me on Trulicity and Jardiance. I&#039;ve tried to take Byetta in the past but had to stop because it made me very sick. I lost weight. But that was because I was throwing up all day. Effective weight loss method but I do NOT recommend it! \nI&#039;ve taken one dose of Trulicity and while I do have mild nausea it is not bad and I have switched from coffee to green tea in the morning. Really helps. That I would recommend. Sugar levels have not dropped significantly but they are dropping. Guess one week won&#039;t work wonders and I have to wait a bit. I don&#039;t know if it is the Trulicity or the Jardiance or the combo of both but I have managed to lose 7 pounds in 5 days.""","dulaglutide ""I was recently referred to a endocrinologist and he started me on Trulicity and Jardiance. I&#039;ve tried to take Byetta in the past but had to stop because it made me very sick. I lost weight. But that was because I was throwing up all day. Effective weight loss method but I do NOT recommend it! \nI&#039;ve taken one dose of Trulicity and while I do have mild nausea it is not bad and I have switched from coffee to green tea in the morning. Really helps. That I would recommend. Sugar levels have not dropped significantly but they are dropping. Guess one week won&#039;t work wonders and I have to wait a bit. I don&#039;t know if it is the Trulicity or the Jardiance or the combo of both but I have managed to lose 7 pounds in 5 days."""

In [55]:
#review_text = " ".join(filtered_df['clean_review'].astype(str))
#drug_text = " ".join(filtered_df['drugName'].astype(str))

In [56]:

#wc = WordCloud(background_color='grey').generate(review_text)
#plt.imshow(wc)#image show
#plt.axis('off')
#plt.title("DrugName",size=25)

In [57]:

#wc = WordCloud(background_color='grey').generate(drug_text)
#plt.imshow(wc)#image show
#plt.axis('off')
#plt.title("DrugName",size=25)

In [58]:
X = filtered_df['combined']
y = filtered_df['condition']

In [59]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [60]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

pipeline = Pipeline([

    ('cleaner', TextCleaner()),

    ('tfidf', TfidfVectorizer(max_features=20000, ngram_range=(1,2))),

    ('model', LogisticRegression(max_iter=1000))

])

In [61]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('cleaner', TextCleaner()),
                ('tfidf',
                 TfidfVectorizer(max_features=20000, ngram_range=(1, 2))),
                ('model', LogisticRegression(max_iter=1000))])

In [62]:
pred = pipeline.predict(X_test)

In [63]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, pred)

print("Accuracy:", accuracy)

Accuracy: 0.9842237361061312

In [64]:
from sklearn.metrics import classification_report

print(classification_report(y_test, pred))

                     precision    recall  f1-score   support

         Depression       0.98      1.00      0.99      1812
   Diabetes, Type 2       0.99      0.98      0.99       505
High Blood Pressure       0.98      0.94      0.96       472

           accuracy                           0.98      2789
          macro avg       0.99      0.97      0.98      2789
       weighted avg       0.98      0.98      0.98      2789

In [65]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, pred)

print(cm)

[[1806    0    6]
 [   5  497    3]
 [  27    3  442]]

In [66]:
pipeline.predict(["sertraline I feel very depressed and anxious"])

array(['Depression'], dtype=object)